import '../notification_model.dart';

class MockNotification{
  static List<MyNotification> notifications = [
  MyNotification(
    sender: '2',
    createdDate: DateTime(2023, 8, 1),
    statusId: 1,
    sendTo: 'Zulfadhli',
    requestType: 'EL',
    requestedDateFrom: DateTime(2023, 7, 20),
    requestedDateTo: DateTime(2023, 7, 25),
    description: 'Sample description 1',
    suggestion: null,
  ),
  MyNotification(
    sender: '4',
    createdDate: DateTime(2023, 8, 2),
    statusId: 2,
    sendTo: 'Cilla Verra',
    requestType: 'AL',
    requestedDateFrom: DateTime(2023, 7, 21),
    requestedDateTo: DateTime(2023, 7, 26),
    description: null,
    suggestion: 'Sample suggestion 2',
  ),
  MyNotification(
    sender: '5',
    createdDate: DateTime(2023, 8, 3),
    statusId: 3,
    sendTo: 'Smith Johnson',
    requestType: 'OT',
    requestedDateFrom: DateTime(2023, 7, 22),
    requestedDateTo: DateTime(2023, 7, 27),
    description: 'Sample description 3',
    suggestion: 'Sample suggestion 3',
  ),
  MyNotification(
    sender: '2',
    createdDate: DateTime(2023, 8, 4),
    statusId: 1,
    sendTo: 'Zulfadhli',
    requestType: 'EL',
    requestedDateFrom: DateTime(2023, 7, 23),
    requestedDateTo: DateTime(2023, 7, 28),
    description: 'Sample description 4',
    suggestion: null,
  ),
  MyNotification(
    sender: '4',
    createdDate: DateTime(2023, 8, 5),
    statusId: 2,
    sendTo: 'Cilla Verra',
    requestType: 'AL',
    requestedDateFrom: DateTime(2023, 7, 24),
    requestedDateTo: DateTime(2023, 7, 29),
    description: null,
    suggestion: 'Sample suggestion 5',
  ),
  MyNotification(
    sender: '5',
    createdDate: DateTime(2023, 8, 6),
    statusId: 3,
    sendTo: 'Smith Johnson',
    requestType: 'OT',
    requestedDateFrom: DateTime(2023, 7, 25),
    requestedDateTo: DateTime(2023, 7, 30),
    description: 'Sample description 6',
    suggestion: 'Sample suggestion 6',
  ),
  MyNotification(
    sender: '2',
    createdDate: DateTime(2023, 8, 7),
    statusId: 1,
    sendTo: 'Zulfadhli',
    requestType: 'EL',
    requestedDateFrom: DateTime(2023, 7, 26),
    requestedDateTo: DateTime(2023, 7, 31),
    description: 'Sample description 7',
    suggestion: null,
  ),
  MyNotification(
    sender: '4',
    createdDate: DateTime(2023, 8, 8),
    statusId: 2,
    sendTo: 'Cilla Verra',
    requestType: 'AL',
    requestedDateFrom: DateTime(2023, 7, 27),
    requestedDateTo: DateTime(2023, 8, 1),
    description: null,
    suggestion: 'Sample suggestion 8',
  ),
  MyNotification(
    sender: '5',
    createdDate: DateTime(2023, 8, 9),
    statusId: 3,
    sendTo: 'Smith Johnson',
    requestType: 'OT',
    requestedDateFrom: DateTime(2023, 7, 28),
    requestedDateTo: DateTime(2023, 8, 2),
    description: 'Sample description 9',
    suggestion: 'Sample suggestion 9',
  ),
  MyNotification(
    sender: '2',
    createdDate: DateTime(2023, 8, 10),
    statusId: 1,
    sendTo: 'Zulfadhli',
    requestType: 'EL',
    requestedDateFrom: DateTime(2023, 7, 29),
    requestedDateTo: DateTime(2023, 8, 3),
    description: 'Sample description 10',
    suggestion: null,
  ),
  MyNotification(
    sender: '4',
    createdDate: DateTime(2023, 8, 11),
    statusId: 2,
    sendTo: 'Cilla Verra',
    requestType: 'AL',
    requestedDateFrom: DateTime(2023, 7, 30),
    requestedDateTo: DateTime(2023, 8, 4),
    description: null,
    suggestion: 'Sample suggestion 11',
  ),
  MyNotification(
    sender: '5',
    createdDate: DateTime(2023, 8, 12),
    statusId: 3,
    sendTo: 'Smith Johnson',
    requestType: 'OT',
    requestedDateFrom: DateTime(2023, 7, 31),
    requestedDateTo: DateTime(2023, 8, 5),
    description: 'Sample description 12',
    suggestion: 'Sample suggestion 12',
  ),
  MyNotification(
    sender: '2',
    createdDate: DateTime(2023, 8, 13),
    statusId: 1,
    sendTo: 'Zulfadhli',
    requestType: 'EL',
    requestedDateFrom: DateTime(2023, 8, 1),
    requestedDateTo: DateTime(2023, 8, 6),
    description: 'Sample description 13',
    suggestion: null,
  ),
  MyNotification(
    sender: '4',
    createdDate: DateTime(2023, 8, 14),
    statusId: 2,
    sendTo: 'Cilla Verra',
    requestType: 'AL',
    requestedDateFrom: DateTime(2023, 8, 2),
    requestedDateTo: DateTime(2023, 8, 7),
    description: null,
    suggestion: 'Sample suggestion 14',
  ),
  MyNotification(
    sender: '5',
    createdDate: DateTime(2023, 8, 15),
    statusId: 1,
    sendTo: 'Smith Johnson',
    requestType: 'OT',
    requestedDateFrom: DateTime(2023, 8, 3),
    requestedDateTo: DateTime(2023, 8, 8),
    description: 'Sample description 15',
    suggestion: 'Sample suggestion 15',
  ),
];

}